repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # Sprawdź najnowszą wersję na GitHubie
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12