# Generated by Django 5.1.7 on 2025-03-31 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessKillHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_name", models.CharField(max_length=255)),
                ("pid", models.IntegerField()),
                ("kill_time", models.DateTimeField(auto_now_add=True)),
                (
                    "killed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot",
                "verbose_name_plural": "Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("duration", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("cpu", models.FloatField()),
                ("memory", models.FloatField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="process_manager.snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot Process",
                "verbose_name_plural": "Snapshot Processes",
                "ordering": ["-snapshot__created_at"],
            },
        ),
    ]
