from .kill_process_via_pid_view import KillProcessViaPidView
from .killed_processes_view import KilledProcessesView
from .login_view import LoginView
from .processes_view import ProcessesView
from .snapshot_details_view import SnapshotDetailsView
from .snapshot_export_view import SnapshotExportView
from .snapshot_list_view import SnapshotsListView
from .take_snapshot_view import TakeSnapshotView
