name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Django Tests with SQLite
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'irrelevant-secret-key'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test -v 2

  lint:
    name: Run Ruff Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

  type-check:
    name: Run Mypy Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Mypy and dependencies
        run: |
          pip install mypy django-stubs
          pip install -r requirements.txt

      - name: Set MYPYPATH
        run: echo "MYPYPATH=$(pwd):$(pwd)/apps" >> $GITHUB_ENV

      - name: Install Stubs
        run: mypy --install-types

      - name: Run Mypy
        run: mypy . --explicit-package-bases
